project_name: geo2tz
before:
  hooks:
    - go mod tidy
signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
builds:
  - id: "geo2tz"
    main: ./main.go
    binary: geo2tz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post: "go run main.go update latest"
changelog:
  use: git
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:latest"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Version }}"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - tzdata