version: 2
updates:
  # Enable version updates for github-actions
  - package-ecosystem: "github-actions"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"